demo-update/EzBooks_Site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ez_main.urls')),
    path('accounts/', include('users.urls')),
]

demo-update/ez_main/urls.py
###############################################################################
#                      Url Patterns for the ez_main app                       #
###############################################################################

from django.urls import path

from . import views

# Url patterns for the ez_main app
app_name = 'ez_main'
urlpatterns = [
    # Home page path
    path('', views.home_page, name='home_page'),

    # About page path
    path('about/', views.about_page, name='about_page'),

    # Class page path
    path('class/', views.class_page, name='class_page'),
]

demo-update/users/urls.py
###############################################################################
#                       Url Patterns for the users app                        #
###############################################################################

from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

app_name = 'users'
urlpatterns = [
    # Login path
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),

    # Register path
    path('register/', views.register, name='register'),

    # Logout path
    path('logout/', views.logout, name='logout'),
]

demo-update/ez_main/models.py
###############################################################################
#                         Models for the ez_main app                          #
###############################################################################

from django.db import models
from users.models import *

class Classes_list(models.Model):
    """ Complete list of all classes """
    class_name      = models.CharField(max_length=200)
    major           = models.CharField(max_length=100)
    class_extension = models.CharField(max_length=200)
    credit          = models.IntegerField(default=25)

    def __str__(self):
        """ Returning a string representation of the model """
        return self.class_name

    def display_classes(self, class1, class2, class3, class4, class5, class6):
        """ Get information for each class in a users class schedule """
        info1 = Classes_list.objects.raw("select id, credit from main_db.ez_main_classes_list where class_name = %s limit 1", [class1]) 
        info2 = Classes_list.objects.raw("select id, credit from main_db.ez_main_classes_list where class_name = %s limit 1", [class2])
        info3 = Classes_list.objects.raw("select id, credit from main_db.ez_main_classes_list where class_name = %s limit 1", [class3])
        info4 = Classes_list.objects.raw("select id, credit from main_db.ez_main_classes_list where class_name = %s limit 1", [class4])
        info5 = Classes_list.objects.raw("select id, credit from main_db.ez_main_classes_list where class_name = %s limit 1", [class5])
        info6 = Classes_list.objects.raw("select id, credit from main_db.ez_main_classes_list where class_name = %s limit 1", [class6])

        return info1[0], info2[0], info3[0], info4[0], info5[0], info6[0]

class Class_schedule(models.Model):
    """ Class schedule associated with each user """
    user_id = models.OneToOneField(User_profile ,on_delete=models.CASCADE, primary_key=True)
    class1  = models.CharField(max_length = 200,  null = True, blank = True)
    class2  = models.CharField(max_length = 200,  null = True, blank = True)
    class3  = models.CharField(max_length = 200,  null = True, blank = True)
    class4  = models.CharField(max_length = 200,  null = True, blank = True)
    class5  = models.CharField(max_length = 200,  null = True, blank = True)
    class6  = models.CharField(max_length = 200,  null = True, blank = True)

    def __str__(self):
        """ Returning a string representation of the model """
        return self.class1 + " - " + self.class2 + " - " + self.class3 + " - " + self.class4 + " - " + self.class5 + " - " + self.class6

    def create_class(self, major):
        """ Create a randomized class schedule based on major linked to a user """
        query_major = major
        random_classes = Classes_list.objects.raw("select id, class_name from main_db.ez_main_classes_list where major = %s order by rand() limit 6", [query_major])
        self.class1 = str(random_classes[0])
        self.class2 = str(random_classes[1])
        self.class3 = str(random_classes[2])
        self.class4 = str(random_classes[3])
        self.class5 = str(random_classes[4])
        self.class6 = str(random_classes[5])

        return random_classes

demo-update/ez_main/views.py
###############################################################################
#                          Views for the ez_main app                          #
###############################################################################

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Classes_list

def home_page(request):
    """ Return the home page for ez_main """
    return render(request, 'ez_main/home_page.html')

def about_page(request):
    """ Return the about page for ez_main """
    return render(request, 'ez_main/about_page.html')

@login_required
def class_page(request):
    """ Return the users class schedule page """
    user    = request.user
    class1  = user.class_schedule.class1
    class2  = user.class_schedule.class2
    class3  = user.class_schedule.class3
    class4  = user.class_schedule.class4
    class5  = user.class_schedule.class5
    class6  = user.class_schedule.class6
    classes = Classes_list()
    display_classes = classes.display_classes(class1, class2, class3, class4, class5, class6)

    return render(request, 'ez_main/class_page.html', {'display_classes': display_classes})

demo-update/ez_main/templates/ez_main/about_page.html
{% extends "ez_main/base.html" %}

<!-- Uses the aboutpage_style.css file located in the ez_main app static folder -->

{% block content %}
<div id="wrapper" class="wrapper">

    <!-- Start Flipbox Style-->
    <div class="section-flipbox section-ptb-120">
        <div class="container">

            <div class="row">
                <!-- Start of Flipbox 1 -->
                <div class="col-lg-4 col-md-6 col-sm-6 col-12">
                    <div class="square-flip charity-flip">
                        <div class="square">
                            <div class="square-container">
                                <span>About</span>
                            </div>
                            <div class="flip-overlay"></div>
                        </div>

                        <div class="square2">
                            <div class="square-container2">
                                <h2>About Simple Scholar</h2>
                                <p>The goal of Simple Scholar is to provide a simple, and convenient method for you, as a busy student, to get your textbooks for the semester!</p>
                            </div>
                            <div class="flip-overlay"></div>
                        </div>
                    </div>
                </div>
                <!-- End of Flipbox 1 -->

                <!-- Start of Flipbox 2 -->
                <div class="col-lg-4 col-md-6 col-sm-6 col-12">
                    <div class="square-flip charity-flip">
                        <div class="square">
                            <div class="square-container">
                                <span>The Team</span>
                            </div>
                            <div class="flip-overlay"></div>
                        </div>

                        <div class="square2">
                            <div class="square-container2">
                                <h2>The Simple Scholar Team</h2>
                                <p>Consisting of several college students who know all to well the experience of getting textbooks the hard way, the Simple Scholar team set out to solve these devastating stuggles for all future students.</p>
                            </div>
                            <div class="flip-overlay"></div>
                        </div>
                    </div>
                </div>
                <!-- End of Flipbox 2 -->

                <!-- Start of Flipbox 3 -->
                <div class="col-lg-4 col-md-6 col-sm-6 col-12">
                    <div class="square-flip charity-flip">
                        <div class="square">
                            <div class="square-container">
                                <span>Services</span>
                            </div>
                            <div class="flip-overlay"></div>
                        </div>

                        <div class="square2">
                            <div class="square-container2">
                                <h2>Services</h2>
                                <p>Simple Scholar offers delivery of your textbook order directly to your dorm room. In addition, all orders are available for pickup at the MK Great Hall within 30 minutes of placing your order.</p>
                            </div>
                            <div class="flip-overlay"></div>
                        </div>
                    </div>
                </div>
                <!-- End of Flipbox 3 -->

            </div>
        </div>
    </div>
    <!-- End Flipbox Style-->

</div>

{% endblock content %}

demo-update/ez_main/templates/ez_main/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>

        <title>Simple Scholar</title>

        <!-- Bootstrap CSS stylesheet -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"/>

        <!-- JQuery and JS For Bootstrap -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

        <!-- Stylesheets for the web pages -->
        {% load static %}
        <link href="{% static "ez_main/base_style.css" %}" rel="stylesheet"/>
        <link href="{% static "ez_main/aboutpage_style.css" %}" rel="stylesheet"/>
        <link href="{% static "ez_main/modal_style.css" %}" rel="stylesheet"/>
        <!-- <link href="{% static "ez_main/plugins.css" %}" rel="stylesheet"/> -->
        
    </head>

<body>
    <!-- Navbar displayed at all times on the project -->
    <!-- Uses the base_styles.css file (Global styles for the pages are in this file as well) -->
    <nav class="navbar-nav navbar-expand-lg bg-dark navbar-dark">
        <a class="navbar-brand" href="{% url 'ez_main:home_page' %}">EzBooks</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="side-navbar-nav navbar-nav ml-auto">
            <!-- Display certain navbar links only when the user is logged in -->
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link">Hello, &nbsp; {{ user.username }}.</a>
                </li>
                <li class="nav-item">
                    <div class="dropdown">
                        <button class="btn btn-primary btn3d" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Personal Info</button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="{% url 'ez_main:class_page' %}">Your Schedule</a>
                            <a class="dropdown-item" href="#">Your Books</a>
                        </div>
                    </div>
                </li>
                <li class="nav-item">
                    <button class="btn btn-primary btn3d">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </button>
                </li>
            {% else %}
                <li class="nav-item">
                    <button class="btn btn-primary btn3d">
                        <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                    </button>
                </li>
                <li class="nav-item">
                    <button class="btn btn-primary btn3d">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </button>
                </li>
            {% endif %}
                <li class="nav-item">
                    <button class="btn btn-primary btn3d" id="last">
                        <a class="nav-link" href="#">Shopping Cart</a>
                    </button>
                </li>
            </ul>
        </div>
    </nav>

    <!-- Container for content loaded with the project views -->
    <div class="content-wrap">
        <div class="body-content">
            <div class="page-header">
                {% block header%}{% endblock header %}
            </div>

            <div class="page-content">
                {% block content %}{% endblock content %}
            </div>
        </div>

        <!-- Global website Footer -->
        <footer class="page-footer">
            <!-- Footer Links -->
            <div class="container-fluid text-center text-md-left">
                <div class="row">
                    <div class="col-md-3 mb-md-0 mb-3">
                        <!-- 1st Column Links -->
                        <h5 class="text-uppercase">Additional Information</h5>
                        <ul class="list-unstyled">
                            <li>
                                <a href="{% url 'ez_main:about_page' %}">About</a>
                            </li>
                            <li>
                                <a href="#!">Contact Info</a>
                            </li>
                        </ul>
                    </div>

                    <div class="col-md-3 mb-md-0 mb-3">
                        <!-- 2nd Column Links -->
                        <h5 class="text-uppercase">Join Simple Scholar</h5>
                        <ul class="list-unstyled">
                            <li>
                                <a href="{% url 'users:login' %}">Login</a>
                            </li>
                            <li>
                                <a href="{% url 'users:register' %}">Register</a>
                            </li>
                        </ul>
                    </div>

                    <div class="col-md-3 mb-md-0 mb-3">
                        <!-- 3rd Column Links -->
                        <h5 class="text-uppercase">Even more links</h5>
                        <ul class="list-unstyled">
                            <li>
                                <a href="#">Stuff</a>
                            </li>
                            <li>
                                <a href="#">Shopping Cart</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="footer-copyright text-center py-3">
                <p>© 2019 Copyright: Ezbooks</p>
            </div>
        </footer>

    </div>

</body>
</html>

demo-update/ez_main/templates/ez_main/class_page.html
{% extends "ez_main/base.html" %}

<!-- Uses the modal_style.css file (located in the ez_main app static folder) -->

{% block content %}

<!-- Bootstrap modal box for the class schedule -->
<div class="modal-dialog text-center">
    <div class= "main-section">
        <div class="modal-content">
            <h4>Class Schedule for {{user.username}}</h4>
            <p>Your major is: &nbsp; {{user.major}}</p>
            <br />
        </div>
    </div>
</div>

<div class="modal-dialog">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th class="text-white bg-dark" scope="col">Extension</th>
                <th class="text-white bg-dark"scope="col">Class Name</th>
                <th class="text-white bg-dark"scope="col">Credit Hrs</th>
            </tr>
        </thead>
        <tbody>
            {% for obj in display_classes %}
            <tr class="table-success">
                <td>{{obj.class_extension}}</td>
                <td>{{obj.class_name}}</td>
                <td id="credit">{{obj.credit}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}

demo-update/ez_main/templates/ez_main/home_page.html
{% extends "ez_main/base.html" %}

<!-- No specific style sheet for the home page -->

{% block content %}
<div class="section-ptb-120">
    <div class="container">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
            </ol>

            {% load static %}
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <a href="{% url 'users:register' %}">
                        <img src="{% static "ez_main/buying_textbooks.jpg" %}" class="d-block w-100" alt="">
                    </a>
                </div>
                <div class="carousel-item">
                    <img src="{% static "ez_main/books.jpg" %}" class="d-block w-100" alt="">
                </div>
                <div class="carousel-item">
                    <img src="{% static "ez_main/bookshelves.jpg" %}" class="d-block w-100" alt="">
                </div>
                <div class="carousel-item">
                    <img src="{% static "ez_main/old_books.jpg" %}" class="d-block w-100" alt="">
                </div>
            </div>

            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>
{% endblock content %}